### ISSUE TITLE
Demo Link not working

### ISSUE THREAD

**Issue by thomasjosephgreco** [mattlewis92/angular2-calendar#41]
@mattlewis92 I am trying to submit it to builtwithangular2.com and I noticed that the demo link wasn't quite working. Is there an alternative ? If you'd like, I can set it up so that it is hosted somewhere, but wanted to bring it to your attention regardless 😄

**Comment by mattlewis92** [comment]
That's intentional, it's simply because I haven't yet finished an initial version. I'm currently introducing breaking changes on a weekly basis while the API is in flux. As soon as it's pretty stable and I don't foresee any more breaking changes I will release 0.1.0. The build script is already setup so that as soon as I do the demo will be auto published to github pages and everything will just work and then I'll start marketing it 😄
